### ISSUE TITLE
Full API access seems excessive

### ISSUE THREAD

**Issue by blargism** [GoogleCloudPlatform/cloud-trace-nodejs#248]
I have a cluster that holds data that falls under HIPAA.  That means a lot of security that a normal app does not get.  The cluster I am using only has open ports to the internet on the boxes with Node.js on them, our app servers.  If I give full API access I would also be giving full cluster control to those boxes, which seems really bad.  One of those boxes is compromised and my cluster is compromised.

My request is two fold:

1. Is there a way we can reduce the API requirements?
2. If the module does not need full access, can we accurately document what access it does need to function correctly?

**Comment by matthewloring** [comment]
The API requirements can be avoided by following the instructions for running outside of the Google Cloud Platform which can be found here https://github.com/GoogleCloudPlatform/cloud-trace-nodejs#running-elsewhere.

For step 2, it may be easier for you to create a service account key instead of running a `gcloud` login command from your production machine. The process for creating and setting up service account keys is documented here https://developers.google.com/identity/protocols/application-default-credentials#howtheywork.

I will update the README to include the service account key option for authorization.

cc @justinbeckwith

**Comment by matthewloring** [comment]
@blargism Please let me know whether service account keys satisfy your use case. Setup is now documented in the readme under the running elsewhere section.

**Comment by blargism** [comment]
I think so.  I will reopen if I run into issues.
