### ISSUE TITLE
Add support for tracing ioredis

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-trace-nodejs#265]
As requested here: https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/pull/262#issuecomment-226107228

**Comment by AdriVanHoudt** [comment]
I understand the maintenance burden.
I don't think both modules differ that much, I choose ioredis because it looked better, can do more (like cluster), which futureproofs it, is used by a large corporation (Alibaba, which is also safer), and does some stuff different which I liked (see https://github.com/luin/ioredis/wiki/Migrating-from-node_redis).
Also they are converging so at one point this request will be obsolete I guess, but not sure what the timeline is on that

**Comment by mattloring** [comment]
We do not currently intend to support ioredis directly. You are welcome to try out the [new plugin api](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/doc/trace-api.md) to build your own plugin. If you do try out the plugin api, please let us know if you have any questions/feedback.

**Comment by AdriVanHoudt** [comment]
@matthewloring I was kind of waiting for the new api ;) when I have time I will definitely look into it!
