### ISSUE TITLE
Mongodb patching next method?

### ISSUE THREAD

**Issue by Meviola** [GoogleCloudPlatform/cloud-trace-nodejs#348]
I have a question, why do you patch the `next` method on the mongodb hook? ([here](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/blob/master/src/hooks/userspace/hook-mongodb-core.js#L131))

Why not patching the `_find` and `_getmore` instead?

**Comment by matthewloring** [comment]
We patch `next` because that is the operation on the module's public interface. We aim for the public interface because we expect most users of a module to reason about the module's behavior in terms of the operations on the public interface. Additionally, it makes our patching more robust since patched function signatures should only change on major version releases. I believe `_find` and `_getmore` are labeled as internal functions in the mongodb-core source. Was there any information you were hoping to make available by patching them separately?

**Comment by matthewloring** [comment]
Closing this for now. Feel free to reopen if you have additional questions.
