### ISSUE TITLE
Support Promises on `runInSpan` or `runInRootSpan`

### ISSUE THREAD

**Issue by melalj** [GoogleCloudPlatform/cloud-trace-nodejs#354]
It would be great to use Promises instead of callback for `runInSpan` or `runInRootSpan`.

Example:
```js
// traceAgent.runInSpan should return myPromise() result
return traceAgent.runInSpan('my-trace', { label: 'mylabel' }, () => {
  return myPromise(); // myPromise() can be either rejected or resolved
});
```

**Comment by matthewloring** [comment]
This sounds like a great idea. There are a few other things we're working on right now on the instrumentation API. We'll revisit this once that work is finished.

**Comment by DominicKramer** [comment]
@melalj I was wondering if I could get some clarification from you?

Does the following code illustrate the functionality you would like supported?  If not, would it be possibly to give an example of the use-case you need supported.  Thanks.
```
traceAPI.runInRootSpan({name: 'root1'}, function(rootSpan) {
        return new Promise(function(resolve, reject) {
          var childSpan1 = traceAPI.createChildSpan({name: 'child1'});
          // do something that is tracked within the child span with name 'child1'
          childSpan1.endSpan();
          resolve({
            // possibly return a child span that will be closed in a `.then()`
            childSpan: traceAPI.createChildSpan({name: 'child2'}),
            rootSpan: rootSpan
          });
        });
      }).then(function(result) {
        // do something that is tracked within the child span with name 'child2'
        var childSpan3 = traceAPI.createChildSpan({name: 'child3'});
        // do something that is tracked within the child span with name 'child3'
        childSpan3.endSpan();
        result.childSpan.endSpan();
        result.rootSpan.endSpan();
        // Note: All of the child spans are within the root span with name 'root1'
      });
```

**Comment by melalj** [comment]
The example that I gave above is a childSpan instead of a root span.
```js
// traceAgent.runInSpan should return myPromise() result
return traceAgent.runInSpan('my-trace', { label: 'mylabel' }, () => {
  return myPromise(); // myPromise() can be either rejected or resolved
});
```
It's more in the case when the rootSpan is auto-detected (for example with express).

The following code is a work around with the current trace API:
```js
const span = traceAgent.startSpan({ label: 'mylabel' });
return myPromise().finally(() => { // Using here bluebird API, can be replaced with more code if you use native JS
  span.endSpan();
});
```

Hope it helps :)

**Comment by matthewloring** [comment]
After looking into this in more detail, we are leaning toward leaving the api as is. We do not currently have this behavior for child spans generated around callbacks because we felt that explicitly placing start/end span calls would make it more clear what precisely is being timed. For promises, in order to capture time spent synchronously in the promise executor the entire promise must be wrapped in a callback to delay its execution (as is done in your example) which leads to a more complex api. Additionally, this API makes it difficult to measure time spent in promise chains where not all promises are attached in the same scope. I'm closing this for now but you are welcome to re-open if you'd like to discuss this API further.
