### ISSUE TITLE
Provide an example with GCLOUD_DIAGNOSTICS_CONFIG usage

### ISSUE THREAD

**Issue by oshalygin** [GoogleCloudPlatform/cloud-trace-nodejs#525]
Reading the README it states that this environment variable can point to the configuration file but its unclear on what that actually means.  Here are the questions that run through my head:

1.  Is this configuration file exported as a javascript object? 
2. Is this configuration file exported as a JSON file?
3. Does this file include the agent startup code? (`require('@google-cloud/trace-agent').start({......`)

I'll try to figure it out on my own and i'll update this issue and follow it up with a PR if there is any interest in this.

**Comment by oshalygin** [comment]
Confirmed what works:

This is performed with just step 1.  To get this working I have the following file in my project:

_./utilities/trace.js_
```javascript

module.exports = {

  // Log levels: 0-disabled,1-error,2-warn,3-info,4-debug
  // Default: 1
  logLevel: 2,

  // Default: true
  enabled: true,

  // If true, information about query parameters and results will be
  // attached to spans representing database operations.
  // Default: false
  enhancedDatabaseReporting: true,

  // The maximum number of characters reported on a label value. This
  // cannot exceed 16383, the maximum value accepted by the service.
  // Default: 512
  maximumLabelValueSize: 512,

  // @type {number} max number of frames to include on traces (0 disables)
  // Default: 10
  stackTraceLimit: 10,

  // We buffer the captured traces for `flushDelaySeconds` before publishing
  // to the trace API; unless the buffer fills up before then.
  // See `bufferSize`.
  // Default: 30
  flushDelaySeconds: 30,

  // If paths are present in this array, then these paths will be ignored before
  // `samplingRate` based decisions are made. Paths must include a leading
  // forward slash and be of the form:
  //   /componentOne/componentTwo/...
  // Paths can additionally be classified by regex in which case any path matching
  // any provided regex will be ignored.
  // We ignore the health checker probes (/_ah/health) by default.
  ignoreUrls: [
    '/_ah/health',
    '/healthz'
  ],

  // An upper bound on the number of traces to gather each second. If set to 0,
  // sampling is disabled and all traces are recorded. Sampling rates greater
  // than 1000 are not supported and will result in at most 1000 samples per
  // second. Some Google Cloud environments may further limit this rate.
  // Default: 10
  samplingRate: 10,

  // The number of transactions we buffer before we publish to the trace
  // API, unless we hit `flushDelaySeconds` first.
  // Default: 1000
  bufferSize: 1000,

  // Specifies the behavior of the trace agent in the case of an uncaught exception.
  // Possible values are:
  //   `ignore`: Take no action. Note that the process may terminate before all the
  //            traces currently buffered have been flushed to the network.
  //   `flush`: Handle the uncaught exception and attempt to publish the traces to
  //            the API. Note that if you have other uncaught exception handlers in your
  //            application, they may chose to terminate the process before the
  //            buffer has been flushed to the network. Also note that if you have no
  //            other terminating uncaught exception handlers in your application, the
  //            error will get swallowed and the application will keep on running. You
  //            should use this option if you have other uncaught exception handlers
  //            that you want to be responsible for terminating the application.
  //   `flushAndExit`: Handle the uncaught exception, make a best effort attempt to
  //            publish the traces to the API, and then terminate the application after
  //            a delay. Note that presence of other uncaught exception handlers may
  //            chose to terminate the application before the buffer has been flushed to
  //            the network.
  // Default: 'ignore'
  onUncaughtException: 'ignore',

  // EXPERIMENTAL:
  // Allows to ignore the requests X-Cloud-Trace-Context -header if set. Setting this
  // to true will cause traces generated by this module to appear separately from other
  // distributed work done by other services on behalf of the same income request. Setting
  // this will also cause sampling decisions made by other distributed components to be
  // ignored. This is useful for aggregating traces generated by different cloud platform
  // projects.
  // Default: false
  ignoreContextHeader: false,

  // The contents of a key file. If this field is set, its contents will be
  // used for authentication instead of your application default credentials.
  // Default: null
  credentials: null,

  // A path to a key file relative to the current working directory. If this
  // field is set, the contents of the pointed file will be used for
  // authentication instead of your application default credentials.
  // If credentials is also set, the value of keyFilename will be ignored.
  // Default: null
  keyFilename: null,

  // For testing purposes only.
  // Used by unit tests to force loading of a new agent if one exists already.
  // Default: false
  forceNewAgent_: false,

  // Specifies the service context with which traces from this application
  // will be associated. This may be useful in filtering traces originating
  // from a specific service within a project. These fields will automatically
  // be set through environment variables on Google App Engine.
  // Default: {service: null, version: null, minorVersion: null}
  serviceContext: {
    service: 'web',
    version: null,
    minorVersion: null
  }
};
```

My initialization script looks as follows:
_package.json_
```json
{
 "scripts": {
    "production": "NODE_ENV=production node --require @google-cloud/trace-agent dist-server/application.production.js"
   }
}
```

And in my Kubernetes deployment configuration:
```yaml
 - name: GCLOUD_DIAGNOSTICS_CONFIG
   value: ./utilities/trace.js
```

**Comment by oshalygin** [comment]
Yeah I because I was seeing alot of errors in regards to not being able to link to the root span as my code was transpiled.  I have an `application.production.js` file which gets babelified but that file has an import to `trace.js` at the very top.

I'll try it with the most recent version and see if I have this issue.

**Comment by matthewloring** [comment]
@oshalygin Have you gotten a chance to give this a try?

**Comment by oshalygin** [comment]
@matthewloring totally forgot was swamped.

I'm going to give this a whirl tomorrow morning when I get into the office.  Thanks!!

**Comment by ctavan** [comment]
Maybe related: I'm using es6 `import` statements which I also have to transpile with babel. Unfortunately this leads to all `require` statements (that result from transpiled `import` statements) being placed at the very top of the main script before any other code (hence also before the `traceAgent.start({ … })` call).

As a workaround I'm now simply using the following wrapper `tracedMain.js` in production which starts the trace agent and then simply requires the actual `main.js`:

```js
// Google Cloud Trace Agent must be started before anything else:
const googleCloudTraceAgent = require('@google-cloud/trace-agent');

if (process.env.NODE_ENV === 'production') {
  googleCloudTraceAgent.start();
}

require('./main');
```

**Comment by oshalygin** [comment]
@ctavan I did that before but I rather not have the entrypoint of my application be `traceMain` or some other file which is specific to the tracing.

Whats a bit confusing to me is why transpiling the trace library results in it not working anymore.  
I tried to require it from the start command but that doesn't work either.

**Comment by matthewloring** [comment]
One of the requirements of this library is that it run before any other modules are required so that it can instrument them at load time. Any transpilation which hoists requires to the top level will interfere with our ability to do this.

**Comment by ofrobots** [comment]
Given these problems with transpilation, I think it would be a good idea to use the library with the node preload module flag: `--require @google-cloud/trace-agent`. This will ensure that the module gets loaded before *everything* else. 

However, that leads to the issue that, since we dropped support for `GCLOUD_DIAGNOSTICS_CONFIG`, it is no longer possible to pass in configuration.

Perhaps it makes sense to bring that (or another) mechanism back to allow people to use `--require`?

**Comment by oshalygin** [comment]
ok that explanation makes alot of sense actually @matthewloring

**Comment by ctavan** [comment]
@ofrobots I have been using `--require @google-cloud/trace-agent` before, but since I wanted to change some configurations I had to write the wrapper mentioned above.

It would be really great to be able to specify a config file through an environment variable since this would render the wrapper unnecessary.

**Comment by oshalygin** [comment]
The discussion is good but I'm curious why the environment variable was removed, maybe the config file wasn't loaded properly or asynchronously after the trace library loads.  

Any thoughts on the env variable config option @matthewloring ?  If not, would you guys consider a PR?  I have some code together I was using as for some tests, I'll clean it up and see what you guys think.

**Comment by ofrobots** [comment]
The environment variable was dropped because it was conceived for the a use-case where we wanted to bundle trace, debug, error-reporting etc. library into a single diagnostics module (the name of the variable suggest that). We ended up dropping those plans, and got rid of the env. var. at the same time.

I think the `--require` use case is good enough for us to bring it back.

A PR for this would be most welcome! Even a partial PR would be fine :heart:.

Some thoughts:
* I would suggest naming the environment variable something trace specific, e.g. `GCLOUD_TRACE_CONFIG`.
* Question: should this config only be used when `--require`d, or more generally. IMO it should be the latter (opposing arguments welcome).

**Comment by ctavan** [comment]
My two cents regarding your thoughs:

* 👍 for `GCLOUD_TRACE_CONFIG`
* I agree that the environment variable should always be respected, irrespective of `--require` or not as implicit behavior is generally hard to reason about.

Another suggestion: I would expect that `GCLOUD_TRACE_CONFIG` is being merged with the defaults and with any additional config supplied to `.start()`. With respect to precedence I would expect `defaults < GCLOUD_TRACE_CONFIG < .start()` so that it would still be possible to override certain configurations by passing them into `.start()`. WDYT?

**Comment by matthewloring** [comment]
Just for some added context, when we originally had configuration specified through the environment, we went with `defaults < .start() < GCLOUD_TRACE_CONFIG` because we thought it would be less intrusive to modify the environment than to make a source change. I could be convinced of either ordering though.

**Comment by ofrobots** [comment]
I think it would be more conventional (i.e. less surprising) to do `defaults < environment < .start()`. I think that is what most users expect.

**Comment by oshalygin** [comment]
I agree, and thats the implementation I have @ofrobots, I'll put the PR out in a few hours after I wrap up a few things at work.

**Comment by matthewloring** [comment]
`GCLOUD_TRACE_CONFIG` is back in https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/commit/4496d3d6f0bdae46a44f7202d73493d829d112b0. We'll get a release out with this functionality soon. Closing this for now.
