### ISSUE TITLE
context loss in @google-cloud/logging

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/cloud-trace-nodejs#555]
Sample app:

```js
require('@google-cloud/trace-agent').start();
const bunyan = require('bunyan');
const lb = require('@google-cloud/logging-bunyan')();

var logger = bunyan.createLogger({
  name: 'my-service',
  streams: [
    lb.stream('info')
  ]
});

const express = require('express');
const app = express();

app.get('/', (req, res) => {
  logger.info('handling request');
  res.status(200).send("Hello from Node.js!");
});

app.listen(process.env.PORT || 8080);
```

The log write operations never show up in Stackdriver trace.

With a higher log level I can see warnings:
```
WARN:@google-cloud/trace-agent: grpc: creating child for an already closed span grpc:/google.logging.v2.LoggingServiceV2/WriteLogEntries / 
```

This suggests that there is likely a promise that gets initialized on the first request and holds onto the context of the first request for all subsequent requests.

**Comment by kjin** [comment]
Traces don't show up because the app sends a response too early; the cloud console truncates/sheds traces that end/start after the root span ends, respectively. Setting a 100+ ms delay shows this behavior (this is from the sample app):

![image](https://user-images.githubusercontent.com/2365820/30559557-e747b9e6-9c69-11e7-92bb-34e581e0b185.png)

The warning message is expected, as the root span ends before the logging library even has a chance to begin publishing.

**Comment by kjin** [comment]
Closing this, as it seems like it's resolved.

If anyone observes the original issue please don't hesitate to re-open this issue and @ me.
