### ISSUE TITLE
Requiring module fails because of lower and upper case disk letter

### ISSUE THREAD

**Issue by QuestionAndAnswer** [GoogleCloudPlatform/cloud-trace-nodejs#557]
I was trying to debug after babel build enabling in our project, but trace-agent started to fail.
If I'm running builded application from npm script like this through nodemon

```./node_modules/.bin/nodemon -w src -w server.js -w index.js ./dist/index.js --delay 5```

everything working fine, but if I'm launching it using Visual Studio Code debugger then error occurs.

![image](https://user-images.githubusercontent.com/6842709/30525392-77fe0f28-9c0e-11e7-971d-6b35b6486a19.png)

I've debug library and, I guess found the issue. This is util.js file of trace-agent.

![image](https://user-images.githubusercontent.com/6842709/30525360-f1b3b04e-9c0d-11e7-8639-075e28b1ec4c.png)

Believe that marked symbols are the same. As you can see this check failing because of lower and upper case difference in disk drive letter.

I'm not sure how I can fix it from VSCode or gulp build perspective.

One addition, node_modules in dist folder with build are symlinked.

Trace-agent has been updated and current version that I'm used in project is 2.2.0.

**Comment by QuestionAndAnswer** [comment]
So, I found workaround for now.
Upper case F letter because of gulp-sym module. By default it's using absolute linking mode. I changed it to use relative and now it's seems to work. 
But, I hope that this issue still can be easily fixed with some checks or excluding disk letter from comparison flow.

**Comment by kjin** [comment]
Thanks for highlighting this issue! Case-insensitivity on Windows is definitely something we should address.

**Comment by kjin** [comment]
Hi @QuestionAndAnswer -- As of 2.6.0 we've changed our module loading mechanism to [`require-in-the-middle`](https://github.com/opbeat/require-in-the-middle). Neither our module nor r-i-t-m uses `_resolveLookupPaths` anymore, so I think the issue of comparing paths is now obsolete.

I'm not sure if this will directly address the issue, but if not, I think the fix will likely need to be there instead of in this module.

Let us know if it doesn't work -- I think it should be easier to introduce a fix in r-i-t-m there.
