### ISSUE TITLE
TraceSpans not garbage collected?

### ISSUE THREAD

**Issue by sanderploegsma** [GoogleCloudPlatform/cloud-trace-nodejs#572]
I recently provisioned one of our apps with this trace agent and it looks like the trace spans are retained in memory for a long time.

Using less than 1 RPS I see a steady increase in memory and a heap dump of a single process on our testing environment (running for about a week, also with less than 1 RPS) contains almost 250K `TraceSpan` objects.

FYI: all configuration was set to default.

**Comment by kjin** [comment]
Thanks for reporting this! Which [traceable modules](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs#what-gets-traced) are you using in your application? Also, any additional information you'd be willing to share will be helpful as well.

**Comment by sanderploegsma** [comment]
It’s a Typescript app running Node 6.11.1, with the following modules:

- Express
- Redis
- Cloud Datastore

**Comment by kjin** [comment]
So after looking into this a bit, I did find a potential culprit for a memory leak (outdated nested dependency on google-auto-auth) -- though whether it could have been the cause is highly dependent on how your app's code is structured. So that being said, if you still have the heap dump -- do you know what objects are retaining the `TraceSpan` objects? Looking for `authClientPromise` in particular.

In the meantime, I'll try to get a PR into `google-gax` to fix this.

**Comment by kjin** [comment]
Ping @sanderploegsma

Please let me know if you can provide any more information. Thanks!

**Comment by ofrobots** [comment]
I believe the issue was due to a leak induced by `google-gax` which is a dependency of other Google Cloud API client libraryes. I believe that has been released now, so this should no longer be a problem. Please reopen if it still is a problem.
