### ISSUE TITLE
Redis Plugin creates phantom child span

### ISSUE THREAD

**Issue by d-winter** [GoogleCloudPlatform/cloud-trace-nodejs#715]
Hey,

I get the following error while setting up the trace agent:

```
INFO:@google-cloud/trace-agent: TraceWriter#scheduleFlush: Performing periodic flush.
INFO:@google-cloud/trace-agent: PluginLoader#activate: Adding require hook.
INFO:@google-cloud/trace-agent: PluginLoader#activate: Activated.
INFO:@google-cloud/trace-agent: TraceAgent#start: Trace Agent activated.
INFO:@google-cloud/trace-agent: PluginWrapper#applyPlugin: [redis@2.8.0] Applying plugin.
INFO:@google-cloud/trace-agent: PluginWrapper#applyPlugin: [http@8.9.1:http] Applying plugin.
WARN:@google-cloud/trace-agent: TraceApi#createChildspan: [redis@2.8.0] Creating phantom child span [redis-auth] because there is no root span.
WARN:@google-cloud/trace-agent: TraceApi#createChildspan: [redis@2.8.0] Creating phantom child span [redis-auth] because there is no root span.
```

These are my dependencies:
```
  "dependencies": {
    "@google-cloud/trace-agent": "^2.6.1",
    "amqplib": "^0.5.2",
    "apollo-fetch": "^0.7.0",
    "env-cmd": "^7.0.0",
    "jsonwebtoken": "^8.2.0",
    "lodash": "^4.17.5",
    "redis": "^2.8.0",
    "winston": "^2.4.1"
  },
```

I load the agent in a separate js file since which requires then the transpiled typescript app. This setup works perfectly without redis.
The spans are shown in google console correctly.
Any idea whats wrong here?

**Comment by kjin** [comment]
This warning message is emitted when we couldn't detect the incoming request with which the redis RPC should correspond. As authentication seems part of the initialization flow rather than on behalf of a request, this warning message is likely a false positive.

It's probably true that there are certain redis commands to which this almost universally applies. I'd like to avoid printing these warning messages, but I also don't want to hardcode these commands to be skipped into the source code itself. We are planning to introduce a feature soon where you should be able to pass config options to the redis plugin, including commands that shouldn't be traced. Would that help?

**Comment by d-winter** [comment]
That would be awesome. So I just continue that way.
Thanks a lot.
